version: "3.9"

services:
  db:
    image: postgres
    container_name: jcu_ball_postgres
    environment:
      - POSTGRES_DB=rsvp
      - POSTGRES_USER=rsvp
      - POSTGRES_PASSWORD=?Js0c2kld
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rsvp"]
      interval: 2s
      timeout: 2s
      retries: 5

  web:
    build: .
    container_name: jcu_ball_web
    environment:
      - DATABASE=postgres
      - SQL_ENGINE=django.db.backends.postgresql
      - POSTGRES_NAME=rsvp
      - POSTGRES_USER=rsvp
      - POSTGRES_PASSWORD=?Js0c2kld
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn jcu_ball.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - .:/home/app/code/
      - static_volume:/home/app/code/staticfiles
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build: ./nginx
    container_name: jcu_ball_nginx
    ports:
      - 443:443
    volumes:
      - static_volume:/home/app/code/staticfiles
      - ./certs:/etc/nginx/certs/
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:

