# Generated by Django 3.1.12 on 2022-03-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(max_length=1)),
                ('last_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=101)),
                ('total_attendees', models.PositiveSmallIntegerField(default=0)),
                ('chicken', models.PositiveSmallIntegerField(default=0)),
                ('beef', models.PositiveSmallIntegerField(default=0)),
                ('fish', models.PositiveSmallIntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('has_paid', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
